services:
  - type: web
    name: Laravel Backend
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:your_app_key_here
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your_database_host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_database_name
      - key: DB_USERNAME
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
